const {chromium}=require('C:/Users/56348/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
  if(!process.env.GUIDE_TEST_PASSWORD)throw Error('GUIDE_TEST_PASSWORD is required');
  const browser=await chromium.launch({headless:true,channel:'chrome',args:['--host-resolver-rules=MAP www.chaoyifan666.fun 127.0.0.1']});
  const page=await browser.newPage({viewport:{width:390,height:844},ignoreHTTPSErrors:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('https://www.chaoyifan666.fun/travel/us-west-lasvegas/#ledger');
  await page.waitForSelector('#cloud-login');
  await page.locator('#cloud-login input').fill(process.env.GUIDE_TEST_PASSWORD);
  await page.locator('#cloud-login button').click();
  await page.waitForFunction(()=>cloudMode==='empty'||cloudMode==='synced');
  const original=await page.evaluate(async()=>{const {data}=await api('GET','state');return data});
  if(await page.locator('[data-action="upload-local"]').count())await page.locator('[data-action="upload-local"]').click();
  await page.waitForFunction(()=>cloudMode==='synced');
  await page.goto('https://www.chaoyifan666.fun/travel/us-west-lasvegas/#daily/3');
  await page.waitForSelector('[data-meal-drawer="d3-12"] summary');
  const before=await page.evaluate(()=>cloudRevision);
  await page.locator('[data-meal-drawer="d3-12"] summary').click();
  await page.locator('[data-pick-meal="d3-12"][data-candidate="1"]').click();
  await page.waitForFunction(before=>cloudRevision>before, before);
  await page.reload();
  await page.waitForFunction(()=>cloudMode==='synced');
  await page.locator('[data-meal-drawer="d3-12"] summary').click();
  assert.match(await page.locator('[data-meal-form="d3-12"] input[name="name"]').inputValue(),/BirdHouse/);
  const restored=await page.evaluate(async state=>{const read=await api('GET','state');return (await api('PUT','state',{revision:read.data.revision,state})).response.status},original.state);
  assert.equal(restored,200);
  await page.goto('https://www.chaoyifan666.fun/travel/us-west-lasvegas/#ledger');
  await page.locator('[data-action="cloud-logout"]').click();
  assert.deepEqual(errors,[]);
  console.log('live UI tunnel test passed: HTTPS render, login, pick, MySQL save, reload, restore, logout');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
