const {chromium}=require('C:/Users/56348/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8787/#map');await page.waitForSelector('#route-svg');
  assert.equal(await page.locator('[data-map-day]').count(),4);
  assert.equal(await page.locator('#route-svg .map-road').count(),8);
  await page.locator('[data-map-variant="core"]').first().click();
  assert.equal(await page.locator('#route-svg .map-road').count(),9);
  assert.equal(await page.locator('#route-svg .backtrack').count(),1);
  assert.match(await page.locator('.atlas-footnotes').innerText(),/15 km、约多 31 分钟/);
  assert.equal(await page.evaluate(()=>DAYS[4].events.some(e=>e.title.includes('折返 Desert View'))),true);
  await page.locator('.atlas-stops [data-map-stop="8"]').click();
  assert.match(await page.locator('.atlas-detail h2').innerText(),/Yavapai.*Desert View/s);
  assert.match(await page.locator('.atlas-detail .btn').getAttribute('href'),/google.com\/maps\/dir/);
  fs.mkdirSync('qa',{recursive:true});
  await page.screenshot({path:'qa/desktop-map-core.png',fullPage:true});
  await page.goto('http://127.0.0.1:8787/#daily/4');
  assert.match(await page.locator('.timeline').innerText(),/折返 Desert View/);
  assert.match(await page.locator('.star-panel h2').innerText(),/Desert View/);
  const integrity=await page.evaluate(()=>DAYS[4].events.flatMap((e,i)=>i&&stamp(DAYS[4],e)<stamp(DAYS[4],DAYS[4].events[i-1],true)?[e.title]:[]));
  assert.deepEqual(integrity,[]);
  await page.reload();assert.match(await page.locator('.timeline').innerText(),/折返 Desert View/);
  await page.locator('.day6-route-picker [data-map-variant="direct"]').click();
  assert.match(await page.locator('.timeline').innerText(),/南门 → Fairfield/);
  assert.match(await page.locator('.star-panel h2').innerText(),/Flagstaff/);
  await page.goto('http://127.0.0.1:8787/#map');
  for(const d of [2,3,4,5]){await page.locator(`[data-map-day="${d}"]`).click();assert.ok(await page.locator('#route-svg .map-road').count()>0);}
  await page.setViewportSize({width:390,height:844});await page.locator('[data-map-day="4"]').click();await page.locator('[data-map-variant="core"]').first().click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile map overflow');
  await page.screenshot({path:'qa/mobile-map-core.png',fullPage:true});
  await page.goto('file:///'+process.cwd().replace(/\\/g,'/')+'/qa/offline.html#map');
  await page.waitForSelector('#route-svg');assert.equal(await page.locator('#route-svg .map-road').count(),8);
  assert.deepEqual(errors,[]);console.log('map QA passed: four days, 10/6 branches, backtrack, sync, persistence, offline, mobile');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
