CREATE DATABASE IF NOT EXISTS canyon_guide CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE canyon_guide;
CREATE TABLE IF NOT EXISTS guide_state (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
  state_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT IGNORE INTO guide_state (id, revision, state_json) VALUES (1, 0, '{}');
CREATE TABLE IF NOT EXISTS guide_sessions (
  token_hash CHAR(64) NOT NULL PRIMARY KEY,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX(expires_at)
);
